version: '3'
services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: your_database
      MYSQL_USER: your_user
      MYSQL_PASSWORD: your_password
    ports:
      - "3306:3306"
    networks:
      - app-network
  web:
    build: .
    ports:
      - "9090:9090"
    depends_on:
      - db
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
